name: taskbudgettracker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2               
  firebase_core: ^3.9.0     
  firebase_auth: ^5.3.4      
  firebase_auth_web: ^5.13.5  
  firebase_storage: ^12.3.7  
  firebase_storage_web: ^3.10.6
  cloud_firestore: ^5.6.0    
  google_sign_in: ^6.0.0
  uuid: ^3.0.7 
  shared_preferences: ^2.0.6
  provider: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0      
  flutter_native_splash: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#580645"
  image: assets/logo.png 
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true

  assets: 
    - assets/app_icon.png      
